const profession = [
      { value: "Educator", label: "Educator" },
      { value: "Engineer", label: "Engineer" },
      { value: "Government Employee", label: "Government Employee" },
      { value: "Information Technology/Systems Support", label: "Information Technology/Systems Support" },
      { value: "Physician Assistant", label: "Physician Assistant" },
      { value: "Physicist: Diagnostic Medical", label: "Physicist: Diagnostic Medical" },
      { value: "Physicist: Nuclear Medicine", label: "Physicist: Nuclear Medicine" },
      { value: "Physicist: Other", label: "Physicist: Other" },
      { value: "Physicist: Therapeutic Medical", label: "Physicist: Therapeutic Medical" },
      { value: "Radiologist: Abdominal Imaging", label: "Radiologist: Abdominal Imaging" },
      { value: "Radiologist: Breast", label: "Radiologist: Breast" },
      { value: "Radiologist: Cardiac Imaging", label: "Radiologist: Cardiac Imaging" },
      { value: "Radiologist: Emergency Imaging", label: "Radiologist: Emergency Imaging" },
      { value: "Radiologist: Interventional", label: "Radiologist: Interventional" },
      { value: "Radiologist: Musculosketal", label: "Radiologist: Musculosketal" },
      { value: "Radiologist: Neurointerventional", label: "Radiologist: Neurointerventional" },
      { value: "Radiologist: Neurology", label: "Radiologist: Neurology" },
      { value: "Radiologist: Other", label: "Radiologist: Other" },
      { value: "Radiologist: Pediatric", label: "Radiologist: Pediatric" },
      { value: "Radiologist: Radiation Oncology", label: "Radiologist: Radiation Oncology" },
      { value: "Radiologist: Thoracic Imaging", label: "Radiologist: Thoracic Imaging" },
      { value: "Radiologist: Vascular ", label: "Radiologist: Vascular " },
      { value: "Radiology Assistant", label: "Radiology Assistant" },
      { value: "Radiology Management", label: "Radiology Management" },
      { value: "Radiology Nurse", label: "Radiology Nurse" },
      { value: "Research Assistant", label: "Research Assistant" },
      { value: "Research Faculty", label: "Research Faculty" },
      { value: "Sonographer", label: "Sonographer" },
      { value: "Technologist: 3D", label: "Technologist: 3D" },
      { value: "Technologist: CT", label: "Technologist: CT" },
      { value: "Technologist: Mammography", label: "Technologist: Mammography" },
      { value: "Technologist: MR", label: "Technologist: MR" },
      { value: "Technologist: Other ", label: "Technologist: Other " },
      { value: "Technologist: PET", label: "Technologist: PET" },
      { value: "Technologist: Ultrasound", label: "Technologist: Ultrasound" },
      { value: "Technologist: X-Ray", label: "Technologist: X-Ray" },
      { value: "Telemedicine/Communications Specialist", label: "Telemedicine/Communications Specialist" },
      { value: "Trainee: Graduate Student", label: "Trainee: Graduate Student" },
      { value: "Trainee: Medical Student", label: "Trainee: Medical Student" },
      { value: "Trainee: Non-Radiology Clinical Fellow", label: "Trainee: Non-Radiology Clinical Fellow" },
      { value: "Trainee: Non-Radiology Resident", label: "Trainee: Non-Radiology Resident" },
      { value: "Trainee: Other ", label: "Trainee: Other " },
      { value: "Trainee: Radiology Clinical Fellow", label: "Trainee: Radiology Clinical Fellow" },
      { value: "Trainee: Radiology Resident", label: "Trainee: Radiology Resident" },
      { value: "Trainee: Research Fellow", label: "Trainee: Research Fellow" },
      { value: "Trainee: Undergraduate", label: "Trainee: Undergraduate" },
      { value: "Other", label: "Other" },
]

export default profession;